name: Build transactions-ihm-angular

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        npm install

    - run: npm install -g @angular/cli > /dev/null

    - name: Lint
      run: ng lint
      continue-on-error: true

    - name: Build
      run: ng build
